### ISSUE TITLE
Error when startupping server

### ISSUE THREAD

**Issue by yaaaaashiki** [yaaaaashiki/restsocket-chat#6]
```
=> Booting Puma
=> Rails 5.0.2 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.12.0 (ruby 2.5.0-p0), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://localhost:3000
Use Ctrl-C to stop
Started GET "/cable" for ::1 at 2018-08-28 14:24:25 +0900
  ActiveRecord::SchemaMigration Load (0.4ms)  SELECT `schema_migrations`.* FROM `schema_migrations`
Started GET "/cable/" [WebSocket] for ::1 at 2018-08-28 14:24:25 +0900
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
  User Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1
Registered connection (Z2lkOi8vc2tpcC10ZXN0L1VzZXIvMQ)
/Users/Soichiro/Desktop/work/Rails/restsocket-chat/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:458: warning: already initialized constant History
/Users/Soichiro/Desktop/work/Rails/restsocket-chat/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:458: warning: previous definition of History was here
Could not execute command from {"command"=>"subscribe", "identifier"=>"{\"channel\":\"History::OnDeletingChannel\"}"}) [LoadError - Unable to autoload constant History::OnDeletingChannel, expected /Users/Soichiro/Desktop/work/Rails/restsocket-chat/app/channels/history/on_deleting_channel.rb to define it]: /Users/Soichiro/Desktop/work/Rails/restsocket-chat/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:512:in `load_missing_constant' | /Users/Soichiro/Desktop/work/Rails/restsocket-chat/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:203:in `const_missing' | /Users/Soichiro/Desktop/work/Rails/restsocket-chat/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.2/lib/active_support/inflector/methods.rb:270:in `const_get' | /Users/Soichiro/Desktop/work/Rails/restsocket-chat/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.2/lib/active_support/inflector/methods.rb:270:in `block in constantize' | /Users/Soichiro/Desktop/work/Rails/restsocket-chat/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.2/lib/active_support/inflector/methods.rb:266:in `each'
DrawingChannel is transmitting the subscription confirmation
DrawingChannel is streaming from drawing_channel
History::OnSendingChannel is transmitting the subscription confirmation
History::OnSendingChannel is streaming from on_sending_channel
MessagesChannel is transmitting the subscription confirmation
MessagesChannel is streaming from messages_channel
/Users/Soichiro/Desktop/work/Rails/restsocket-chat/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:458: warning: already initialized constant PageTransition
/Users/Soichiro/Desktop/work/Rails/restsocket-chat/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:458: warning: previous definition of PageTransition was here
Could not execute command from {"command"=>"subscribe", "identifier"=>"{\"channel\":\"PageTransition::PageBackChannel\"}"}) [LoadError - Unable to autoload constant PageTransition::PageBackChannel, expected /Users/Soichiro/Desktop/work/Rails/restsocket-chat/app/channels/page_transition/page_back_channel.rb to define it]: /Users/Soichiro/Desktop/work/Rails/restsocket-chat/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:512:in `load_missing_constant' | /Users/Soichiro/Desktop/work/Rails/restsocket-chat/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:203:in `const_missing' | /Users/Soichiro/Desktop/work/Rails/restsocket-chat/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.2/lib/active_support/inflector/methods.rb:270:in `const_get' | /Users/Soichiro/Desktop/work/Rails/restsocket-chat/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.2/lib/active_support/inflector/methods.rb:270:in `block in constantize' | /Users/Soichiro/Desktop/work/Rails/restsocket-chat/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.2/lib/active_support/inflector/methods.rb:266:in `each'
PageTransition::PageForwardChannel is transmitting the subscription confirmation
PageTransition::PageForwardChannel is streaming from page_forward_channel
```

**Comment by yaaaaashiki** [comment]
Resolved
